[platformio]
default_envs = native

[env:native]
platform = native
src_dir = simulator/native
build_flags = -std=c++17

[env:prototype_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
src_dir = firmware/main
build_flags = -DBOARD_PROFILE_PROTOTYPE_C3_GC9A01=1
