#pragma once

#include "lvgl.h"

// Picks a Montserrat face by target pixel size.
//
// Pages author type as a glyph height measured off the Figma SVG, then ask for the nearest face at
// or below it -- the same "reference-design pixels scaled to the live panel" convention the rest of
// the geometry uses. Shared rather than per-page because the idle, odometer and dial pages all need
// it and must not drift apart on which size they round to.
//
// These are NOT LVGL's built-in fonts. They are subsetted faces generated by
// tools/build_font_subset.py from design/fonts/fonts_manifest.json, because the built-ins carry all
// of ASCII plus 61 FontAwesome symbols at every size -- 231 KB of flash, roughly a fifth of the C3's
// app partition, to draw digits and four compass letters.
//
// CONSEQUENCE, and the one thing to remember here: each size only has the characters the manifest
// lists for it. Giving a label new text may need a manifest edit and a regeneration, or the new
// characters render as empty boxes. Sizes fed by phone-supplied strings (street name, ETA) are kept
// full-ASCII for exactly that reason. Metrics are inherited from the full faces, so switching to
// these moved no label.
const lv_font_t *montserrat_at_most(int32_t px);
