// Auto-generated by Google Icons Archive/Icon JSON/build_icons.py from
// maneuvers.json -- do not edit by hand, edit maneuvers.json instead.
// C twin of Demo/icons-data.js -- see Demo/demo.js for the renderer this data feeds.
#pragma once

#include <stddef.h>
#include <stdint.h>

typedef struct { float x, y; } nav_pt_t;

typedef struct {
    const nav_pt_t *main_path;
    size_t main_count;
    const nav_pt_t *secondary_path;
    size_t secondary_count;
    nav_pt_t frame_center;
} nav_icon_data_t;

typedef enum {
    NAV_RENDER_STRAIGHT,
    NAV_RENDER_TURN_RIGHT,
    NAV_RENDER_TURN_LEFT,
    NAV_RENDER_TURN_SLIGHT_RIGHT,
    NAV_RENDER_TURN_SLIGHT_LEFT,
    NAV_RENDER_U_TURN_RIGHT,
    NAV_RENDER_U_TURN_LEFT,
    NAV_RENDER_ROUNDABOUT_RIGHT,
    NAV_RENDER_ROUNDABOUT_STRAIGHT,
    NAV_RENDER_ROUNDABOUT_LEFT,
    NAV_RENDER_RIGHT_MERGE,
    NAV_RENDER_MERGE_LEFT,
    NAV_RENDER_COUNT,
} nav_render_icon_t;

static const nav_pt_t nav_icon_straight_main[] = {{0.00f, 0.00f}, {0.00f, -28.90f}, {0.00f, -57.80f}, {0.00f, -86.70f}, {0.00f, -115.60f}, {0.00f, -144.40f}, {0.00f, -173.30f}, {0.00f, -202.20f}, {0.00f, -231.10f}, {0.00f, -260.00f}};
static const nav_pt_t nav_icon_turn_right_main[] = {{0.00f, 0.00f}, {0.00f, -32.50f}, {0.00f, -65.00f}, {0.00f, -97.50f}, {0.00f, -130.00f}, {0.40f, -137.20f}, {1.70f, -144.40f}, {3.90f, -151.30f}, {6.90f, -157.90f}, {10.60f, -164.10f}, {15.10f, -169.80f}, {20.20f, -174.90f}, {25.90f, -179.40f}, {32.10f, -183.10f}, {38.70f, -186.10f}, {45.60f, -188.30f}, {52.80f, -189.60f}, {60.00f, -190.00f}, {88.00f, -190.00f}, {116.00f, -190.00f}, {144.00f, -190.00f}, {172.00f, -190.00f}, {200.00f, -190.00f}};
static const nav_pt_t nav_icon_turn_left_main[] = {{-0.00f, 0.00f}, {-0.00f, -32.50f}, {-0.00f, -65.00f}, {-0.00f, -97.50f}, {-0.00f, -130.00f}, {-0.40f, -137.20f}, {-1.70f, -144.40f}, {-3.90f, -151.30f}, {-6.90f, -157.90f}, {-10.60f, -164.10f}, {-15.10f, -169.80f}, {-20.20f, -174.90f}, {-25.90f, -179.40f}, {-32.10f, -183.10f}, {-38.70f, -186.10f}, {-45.60f, -188.30f}, {-52.80f, -189.60f}, {-60.00f, -190.00f}, {-88.00f, -190.00f}, {-116.00f, -190.00f}, {-144.00f, -190.00f}, {-172.00f, -190.00f}, {-200.00f, -190.00f}};
static const nav_pt_t nav_icon_turn_slight_right_main[] = {{0.00f, 0.00f}, {0.00f, -32.50f}, {0.00f, -65.00f}, {0.00f, -97.50f}, {0.00f, -130.00f}, {0.40f, -137.30f}, {1.80f, -144.50f}, {4.00f, -151.50f}, {7.00f, -158.20f}, {10.90f, -164.40f}, {27.50f, -188.20f}, {44.10f, -211.90f}, {60.80f, -235.70f}, {77.40f, -259.40f}, {94.00f, -283.20f}};
static const nav_pt_t nav_icon_turn_slight_left_main[] = {{-0.00f, 0.00f}, {-0.00f, -32.50f}, {-0.00f, -65.00f}, {-0.00f, -97.50f}, {-0.00f, -130.00f}, {-0.40f, -137.30f}, {-1.80f, -144.50f}, {-4.00f, -151.50f}, {-7.00f, -158.20f}, {-10.90f, -164.40f}, {-27.50f, -188.20f}, {-44.10f, -211.90f}, {-60.80f, -235.70f}, {-77.40f, -259.40f}, {-94.00f, -283.20f}};
static const nav_pt_t nav_icon_u_turn_right_main[] = {{0.00f, 0.00f}, {0.00f, -30.00f}, {0.00f, -60.00f}, {0.00f, -90.00f}, {0.00f, -120.00f}, {0.00f, -150.00f}, {0.00f, -180.00f}, {0.50f, -188.40f}, {2.00f, -196.80f}, {4.50f, -204.80f}, {8.00f, -212.50f}, {12.40f, -219.80f}, {17.60f, -226.40f}, {23.60f, -232.40f}, {30.20f, -237.60f}, {37.50f, -242.00f}, {45.20f, -245.50f}, {53.20f, -248.00f}, {61.60f, -249.50f}, {70.00f, -250.00f}, {78.40f, -249.50f}, {86.80f, -248.00f}, {94.80f, -245.50f}, {102.50f, -242.00f}, {109.80f, -237.60f}, {116.40f, -232.40f}, {122.40f, -226.40f}, {127.60f, -219.80f}, {132.00f, -212.50f}, {135.50f, -204.80f}, {138.00f, -196.80f}, {139.50f, -188.40f}, {140.00f, -180.00f}, {140.00f, -152.00f}, {140.00f, -124.00f}, {140.00f, -96.00f}, {140.00f, -68.00f}, {140.00f, -40.00f}};
static const nav_pt_t nav_icon_u_turn_left_main[] = {{-0.00f, 0.00f}, {-0.00f, -30.00f}, {-0.00f, -60.00f}, {-0.00f, -90.00f}, {-0.00f, -120.00f}, {-0.00f, -150.00f}, {-0.00f, -180.00f}, {-0.50f, -188.40f}, {-2.00f, -196.80f}, {-4.50f, -204.80f}, {-8.00f, -212.50f}, {-12.40f, -219.80f}, {-17.60f, -226.40f}, {-23.60f, -232.40f}, {-30.20f, -237.60f}, {-37.50f, -242.00f}, {-45.20f, -245.50f}, {-53.20f, -248.00f}, {-61.60f, -249.50f}, {-70.00f, -250.00f}, {-78.40f, -249.50f}, {-86.80f, -248.00f}, {-94.80f, -245.50f}, {-102.50f, -242.00f}, {-109.80f, -237.60f}, {-116.40f, -232.40f}, {-122.40f, -226.40f}, {-127.60f, -219.80f}, {-132.00f, -212.50f}, {-135.50f, -204.80f}, {-138.00f, -196.80f}, {-139.50f, -188.40f}, {-140.00f, -180.00f}, {-140.00f, -152.00f}, {-140.00f, -124.00f}, {-140.00f, -96.00f}, {-140.00f, -68.00f}, {-140.00f, -40.00f}};
static const nav_pt_t nav_icon_roundabout_right_main[] = {{0.00f, 0.00f}, {0.00f, -35.00f}, {0.00f, -70.00f}, {-0.20f, -72.50f}, {-0.60f, -74.90f}, {-1.40f, -77.30f}, {-2.40f, -79.60f}, {-3.80f, -81.70f}, {-5.30f, -83.60f}, {-7.10f, -85.30f}, {-9.10f, -86.80f}, {-11.30f, -88.00f}, {-13.60f, -88.90f}, {-16.00f, -89.60f}, {-25.50f, -92.20f}, {-34.60f, -95.90f}, {-43.20f, -100.70f}, {-51.20f, -106.50f}, {-58.30f, -113.20f}, {-64.60f, -120.80f}, {-69.90f, -129.10f}, {-74.20f, -138.00f}, {-77.30f, -147.30f}, {-79.20f, -157.00f}, {-80.00f, -166.80f}, {-79.50f, -176.60f}, {-77.90f, -186.30f}, {-75.00f, -195.70f}, {-71.00f, -204.70f}, {-66.00f, -213.20f}, {-59.90f, -221.00f}, {-53.00f, -227.90f}, {-45.20f, -234.00f}, {-36.80f, -239.00f}, {-27.80f, -243.00f}, {-18.30f, -245.80f}, {-8.60f, -247.50f}, {1.20f, -248.00f}, {11.00f, -247.20f}, {20.70f, -245.30f}, {30.00f, -242.10f}, {38.90f, -237.90f}, {47.20f, -232.60f}, {54.80f, -226.30f}, {61.50f, -219.10f}, {67.30f, -211.20f}, {72.10f, -202.60f}, {75.80f, -193.50f}, {78.40f, -184.00f}, {79.00f, -181.60f}, {80.00f, -179.30f}, {81.20f, -177.10f}, {82.70f, -175.10f}, {84.40f, -173.30f}, {86.30f, -171.70f}, {88.40f, -170.40f}, {90.70f, -169.40f}, {93.10f, -168.60f}, {95.50f, -168.10f}, {98.00f, -168.00f}, {128.00f, -168.00f}, {158.00f, -168.00f}, {188.00f, -168.00f}};
static const nav_pt_t nav_icon_roundabout_straight_main[] = {{0.00f, 0.00f}, {0.00f, -25.00f}, {0.00f, -50.00f}, {-0.10f, -52.40f}, {-0.60f, -54.80f}, {-1.30f, -57.20f}, {-2.40f, -59.40f}, {-3.60f, -61.50f}, {-5.20f, -63.40f}, {-6.90f, -65.10f}, {-8.80f, -66.60f}, {-11.00f, -67.80f}, {-13.20f, -68.80f}, {-15.60f, -69.50f}, {-23.80f, -71.90f}, {-31.60f, -75.30f}, {-39.00f, -79.60f}, {-45.80f, -84.80f}, {-51.90f, -90.80f}, {-57.30f, -97.50f}, {-61.80f, -104.80f}, {-65.30f, -112.60f}, {-67.90f, -120.80f}, {-69.50f, -129.20f}, {-70.00f, -137.70f}, {-69.50f, -146.30f}, {-67.90f, -154.70f}, {-65.30f, -162.90f}, {-61.80f, -170.70f}, {-57.30f, -178.00f}, {-51.90f, -184.70f}, {-45.80f, -190.70f}, {-39.00f, -195.90f}, {-31.60f, -200.20f}, {-23.80f, -203.60f}, {-15.60f, -206.00f}, {-13.20f, -206.70f}, {-11.00f, -207.70f}, {-8.80f, -208.90f}, {-6.90f, -210.40f}, {-5.20f, -212.10f}, {-3.60f, -214.00f}, {-2.40f, -216.10f}, {-1.30f, -218.30f}, {-0.60f, -220.70f}, {-0.10f, -223.10f}, {0.00f, -225.50f}, {0.00f, -258.80f}, {0.00f, -292.20f}, {0.00f, -325.50f}};
static const nav_pt_t nav_icon_roundabout_left_main[] = {{0.00f, 0.00f}, {0.00f, -26.70f}, {0.00f, -53.30f}, {0.00f, -80.00f}, {-0.10f, -82.40f}, {-0.60f, -84.80f}, {-1.30f, -87.20f}, {-2.40f, -89.40f}, {-3.60f, -91.50f}, {-5.20f, -93.40f}, {-6.90f, -95.10f}, {-8.80f, -96.60f}, {-11.00f, -97.80f}, {-13.20f, -98.80f}, {-15.60f, -99.50f}, {-23.90f, -102.00f}, {-31.90f, -105.50f}, {-39.40f, -109.90f}, {-46.30f, -115.30f}, {-52.50f, -121.40f}, {-57.80f, -128.30f}, {-62.30f, -135.80f}, {-65.80f, -143.80f}, {-68.20f, -152.20f}, {-68.90f, -154.50f}, {-69.90f, -156.80f}, {-71.10f, -158.90f}, {-72.60f, -160.80f}, {-74.30f, -162.60f}, {-76.30f, -164.10f}, {-78.30f, -165.40f}, {-80.60f, -166.40f}, {-82.90f, -167.20f}, {-85.30f, -167.60f}, {-87.70f, -167.70f}, {-116.50f, -167.70f}, {-145.20f, -167.70f}, {-174.00f, -167.70f}, {-202.70f, -167.70f}};
static const nav_pt_t nav_icon_right_merge_main[] = {{0.00f, 0.00f}, {0.00f, -28.90f}, {0.00f, -57.80f}, {0.00f, -86.70f}, {0.00f, -115.60f}, {0.00f, -144.40f}, {0.00f, -173.30f}, {0.00f, -202.20f}, {0.00f, -231.10f}, {0.00f, -260.00f}};
static const nav_pt_t nav_icon_right_merge_secondary[] = {{190.00f, -40.00f}, {179.40f, -54.10f}, {167.90f, -67.50f}, {155.40f, -80.00f}, {142.20f, -91.70f}, {128.20f, -102.40f}, {113.50f, -112.20f}, {98.20f, -120.90f}, {82.30f, -128.60f}, {65.90f, -135.20f}};
static const nav_pt_t nav_icon_merge_left_main[] = {{-0.00f, 0.00f}, {-0.00f, -28.90f}, {-0.00f, -57.80f}, {-0.00f, -86.70f}, {-0.00f, -115.60f}, {-0.00f, -144.40f}, {-0.00f, -173.30f}, {-0.00f, -202.20f}, {-0.00f, -231.10f}, {-0.00f, -260.00f}};
static const nav_pt_t nav_icon_merge_left_secondary[] = {{-190.00f, -40.00f}, {-179.40f, -54.10f}, {-167.90f, -67.50f}, {-155.40f, -80.00f}, {-142.20f, -91.70f}, {-128.20f, -102.40f}, {-113.50f, -112.20f}, {-98.20f, -120.90f}, {-82.30f, -128.60f}, {-65.90f, -135.20f}};

static const nav_icon_data_t NAV_ICON_DATA[NAV_RENDER_COUNT] = {
    [NAV_RENDER_STRAIGHT] = { nav_icon_straight_main, 10, NULL, 0, {0.0f, -130.0f} },
    [NAV_RENDER_TURN_RIGHT] = { nav_icon_turn_right_main, 23, NULL, 0, {70.0f, -120.0f} },
    [NAV_RENDER_TURN_LEFT] = { nav_icon_turn_left_main, 23, NULL, 0, {-70.0f, -120.0f} },
    [NAV_RENDER_TURN_SLIGHT_RIGHT] = { nav_icon_turn_slight_right_main, 15, NULL, 0, {34.6f, -145.5f} },
    [NAV_RENDER_TURN_SLIGHT_LEFT] = { nav_icon_turn_slight_left_main, 15, NULL, 0, {-34.6f, -145.5f} },
    [NAV_RENDER_U_TURN_RIGHT] = { nav_icon_u_turn_right_main, 38, NULL, 0, {70.0f, -130.0f} },
    [NAV_RENDER_U_TURN_LEFT] = { nav_icon_u_turn_left_main, 38, NULL, 0, {-70.0f, -130.0f} },
    [NAV_RENDER_ROUNDABOUT_RIGHT] = { nav_icon_roundabout_right_main, 63, NULL, 0, {40.0f, -145.0f} },
    [NAV_RENDER_ROUNDABOUT_STRAIGHT] = { nav_icon_roundabout_straight_main, 50, NULL, 0, {-0.0f, -165.0f} },
    [NAV_RENDER_ROUNDABOUT_LEFT] = { nav_icon_roundabout_left_main, 39, NULL, 0, {-55.0f, -136.6f} },
    [NAV_RENDER_RIGHT_MERGE] = { nav_icon_right_merge_main, 10, nav_icon_right_merge_secondary, 10, {70.0f, -130.0f} },
    [NAV_RENDER_MERGE_LEFT] = { nav_icon_merge_left_main, 10, nav_icon_merge_left_secondary, 10, {-70.0f, -130.0f} },
};

static const nav_pt_t NAV_ARROWHEAD_PERIMETER[] = {{-47.00f, 180.00f}, {-137.00f, 270.00f}, {-203.00f, 204.00f}, {0.00f, 0.00f}, {203.00f, 204.00f}, {137.00f, 270.00f}, {47.00f, 180.00f}};
#define NAV_ARROWHEAD_VERT_COUNT 7
static const nav_pt_t NAV_ARROWHEAD_TIP = {0.0f, 0.0f};
static const float NAV_ARROWHEAD_HEAD_BASE_HALF_WIDTH = 47.0f;
static const float NAV_ARROWHEAD_HEAD_BASE_DEPTH = 180.0f;
static const uint8_t NAV_ARROWHEAD_TRIS[][3] = {
    {0, 1, 2},
    {0, 2, 3},
    {6, 0, 3},
    {6, 3, 4},
    {4, 5, 6},
};
#define NAV_ARROWHEAD_TRI_COUNT 5

