// Auto-generated by Google Icons Archive/Icon JSON/build_icons.py from
// maneuvers.json -- do not edit by hand, edit maneuvers.json instead.
// C twin of Demo/icons-data.js -- see Demo/demo.js for the renderer this data feeds.
#pragma once

#include <stddef.h>
#include <stdint.h>

typedef struct { float x, y; } nav_pt_t;

// The maneuver body ships as EXACT primitives (the same straights/curves maneuvers.json
// declares), not as sampled points: the firmware renders a curve with one lv_draw_arc, so
// there are no quad-to-quad joints inside it to seam. Demo/icons-data.js still gets the
// tessellated point path -- the JS canvas demo strokes a Path2D and has no such problem.
// Angles are degrees, x right / y DOWN (SVG convention, matching maneuvers.json).
// heading0 = travel direction at p0; turn_deg is signed (+ = right/toward +x) and 0 for
// lines; length is arc length for arcs (radius * |turn_deg| * pi/180); start_dist/end_dist
// are cumulative along the maneuver, which is what the reveal animation slices on.
typedef enum { NAV_SEG_LINE = 0, NAV_SEG_ARC = 1 } nav_seg_type_t;

typedef struct {
    nav_seg_type_t type;
    nav_pt_t p0;
    float heading0;
    float length;
    float radius;
    float turn_deg;
    float start_dist;
    float end_dist;
} nav_segment_t;

typedef struct {
    const nav_segment_t *main_segments;
    size_t main_segment_count;
    const nav_pt_t *secondary_path;
    size_t secondary_count;
    nav_pt_t frame_center;
} nav_icon_data_t;

typedef enum {
    NAV_RENDER_STRAIGHT,
    NAV_RENDER_TURN_RIGHT,
    NAV_RENDER_TURN_LEFT,
    NAV_RENDER_TURN_SLIGHT_RIGHT,
    NAV_RENDER_TURN_SLIGHT_LEFT,
    NAV_RENDER_U_TURN_RIGHT,
    NAV_RENDER_U_TURN_LEFT,
    NAV_RENDER_ROUNDABOUT_RIGHT,
    NAV_RENDER_ROUNDABOUT_STRAIGHT,
    NAV_RENDER_ROUNDABOUT_LEFT,
    NAV_RENDER_RIGHT_MERGE,
    NAV_RENDER_MERGE_LEFT,
    NAV_RENDER_COUNT,
} nav_render_icon_t;

static const nav_segment_t nav_icon_straight_main[] = {
    {NAV_SEG_LINE, {0.00f, 0.00f}, -90.0000f, 260.0000f, 0.0000f, 0.0000f, 0.0000f, 260.0000f},
};
static const nav_segment_t nav_icon_turn_right_main[] = {
    {NAV_SEG_LINE, {0.00f, 0.00f}, -90.0000f, 130.0000f, 0.0000f, 0.0000f, 0.0000f, 130.0000f},
    {NAV_SEG_ARC, {0.00f, -130.00f}, -90.0000f, 94.2478f, 60.0000f, 90.0000f, 130.0000f, 224.2478f},
    {NAV_SEG_LINE, {60.00f, -190.00f}, 0.0000f, 140.0000f, 0.0000f, 0.0000f, 224.2478f, 364.2478f},
};
static const nav_segment_t nav_icon_turn_left_main[] = {
    {NAV_SEG_LINE, {-0.00f, 0.00f}, -90.0000f, 130.0000f, 0.0000f, -0.0000f, 0.0000f, 130.0000f},
    {NAV_SEG_ARC, {-0.00f, -130.00f}, -90.0000f, 94.2478f, 60.0000f, -90.0000f, 130.0000f, 224.2478f},
    {NAV_SEG_LINE, {-60.00f, -190.00f}, 180.0000f, 140.0000f, 0.0000f, -0.0000f, 224.2478f, 364.2478f},
};
static const nav_segment_t nav_icon_turn_slight_right_main[] = {
    {NAV_SEG_LINE, {0.00f, 0.00f}, -90.0000f, 130.0000f, 0.0000f, 0.0000f, 0.0000f, 130.0000f},
    {NAV_SEG_ARC, {0.00f, -130.00f}, -90.0000f, 36.6519f, 60.0000f, 35.0000f, 130.0000f, 166.6519f},
    {NAV_SEG_LINE, {10.85f, -164.41f}, -55.0000f, 145.0000f, 0.0000f, 0.0000f, 166.6519f, 311.6519f},
};
static const nav_segment_t nav_icon_turn_slight_left_main[] = {
    {NAV_SEG_LINE, {-0.00f, 0.00f}, -90.0000f, 130.0000f, 0.0000f, -0.0000f, 0.0000f, 130.0000f},
    {NAV_SEG_ARC, {-0.00f, -130.00f}, -90.0000f, 36.6519f, 60.0000f, -35.0000f, 130.0000f, 166.6519f},
    {NAV_SEG_LINE, {-10.85f, -164.41f}, -125.0000f, 145.0000f, 0.0000f, -0.0000f, 166.6519f, 311.6519f},
};
static const nav_segment_t nav_icon_u_turn_right_main[] = {
    {NAV_SEG_LINE, {0.00f, 0.00f}, -90.0000f, 180.0000f, 0.0000f, 0.0000f, 0.0000f, 180.0000f},
    {NAV_SEG_ARC, {0.00f, -180.00f}, -90.0000f, 219.9115f, 70.0000f, 180.0000f, 180.0000f, 399.9115f},
    {NAV_SEG_LINE, {140.00f, -180.00f}, 90.0000f, 140.0000f, 0.0000f, 0.0000f, 399.9115f, 539.9115f},
};
static const nav_segment_t nav_icon_u_turn_left_main[] = {
    {NAV_SEG_LINE, {-0.00f, 0.00f}, -90.0000f, 180.0000f, 0.0000f, -0.0000f, 0.0000f, 180.0000f},
    {NAV_SEG_ARC, {-0.00f, -180.00f}, -90.0000f, 219.9115f, 70.0000f, -180.0000f, 180.0000f, 399.9115f},
    {NAV_SEG_LINE, {-140.00f, -180.00f}, 90.0000f, 140.0000f, 0.0000f, -0.0000f, 399.9115f, 539.9115f},
};
static const nav_segment_t nav_icon_roundabout_right_main[] = {
    {NAV_SEG_LINE, {0.00f, 0.00f}, -90.0000f, 70.0000f, 0.0000f, 0.0000f, 0.0000f, 70.0000f},
    {NAV_SEG_ARC, {0.00f, -70.00f}, -90.0000f, 27.3888f, 20.0000f, -78.4630f, 70.0000f, 97.3888f},
    {NAV_SEG_ARC, {-16.00f, -89.60f}, -168.4630f, 344.7739f, 80.0000f, 246.9261f, 97.3888f, 442.1626f},
    {NAV_SEG_ARC, {78.38f, -183.98f}, 78.4630f, 27.3888f, 20.0000f, -78.4630f, 442.1626f, 469.5514f},
    {NAV_SEG_LINE, {97.98f, -167.98f}, 0.0000f, 90.0000f, 0.0000f, 0.0000f, 469.5514f, 559.5514f},
};
static const nav_segment_t nav_icon_roundabout_straight_main[] = {
    {NAV_SEG_LINE, {0.00f, 0.00f}, -90.0000f, 50.0000f, 0.0000f, 0.0000f, 0.0000f, 50.0000f},
    {NAV_SEG_ARC, {0.00f, -50.00f}, -90.0000f, 26.9341f, 20.0000f, -77.1604f, 50.0000f, 76.9341f},
    {NAV_SEG_ARC, {-15.56f, -69.50f}, -167.1604f, 188.5385f, 70.0000f, 154.3208f, 76.9341f, 265.4725f},
    {NAV_SEG_ARC, {-15.56f, -206.00f}, -12.8396f, 26.9341f, 20.0000f, -77.1604f, 265.4725f, 292.4066f},
    {NAV_SEG_LINE, {0.00f, -225.50f}, -90.0000f, 100.0000f, 0.0000f, 0.0000f, 292.4066f, 392.4066f},
};
static const nav_segment_t nav_icon_roundabout_left_main[] = {
    {NAV_SEG_LINE, {0.00f, 0.00f}, -90.0000f, 80.0000f, 0.0000f, 0.0000f, 0.0000f, 80.0000f},
    {NAV_SEG_ARC, {0.00f, -80.00f}, -90.0000f, 26.9341f, 20.0000f, -77.1604f, 80.0000f, 106.9341f},
    {NAV_SEG_ARC, {-15.56f, -99.50f}, -167.1604f, 78.5827f, 70.0000f, 64.3208f, 106.9341f, 185.5168f},
    {NAV_SEG_ARC, {-68.25f, -152.19f}, -102.8396f, 26.9341f, 20.0000f, -77.1604f, 185.5168f, 212.4508f},
    {NAV_SEG_LINE, {-87.75f, -167.75f}, -180.0000f, 115.0000f, 0.0000f, 0.0000f, 212.4508f, 327.4508f},
};
static const nav_segment_t nav_icon_right_merge_main[] = {
    {NAV_SEG_LINE, {0.00f, 0.00f}, -90.0000f, 260.0000f, 0.0000f, 0.0000f, 0.0000f, 260.0000f},
};
static const nav_pt_t nav_icon_right_merge_secondary[] = {{190.00f, -40.00f}, {179.40f, -54.10f}, {167.90f, -67.50f}, {155.40f, -80.00f}, {142.20f, -91.70f}, {128.20f, -102.40f}, {113.50f, -112.20f}, {98.20f, -120.90f}, {82.30f, -128.60f}, {65.90f, -135.20f}};
static const nav_segment_t nav_icon_merge_left_main[] = {
    {NAV_SEG_LINE, {-0.00f, 0.00f}, -90.0000f, 260.0000f, 0.0000f, -0.0000f, 0.0000f, 260.0000f},
};
static const nav_pt_t nav_icon_merge_left_secondary[] = {{-190.00f, -40.00f}, {-179.40f, -54.10f}, {-167.90f, -67.50f}, {-155.40f, -80.00f}, {-142.20f, -91.70f}, {-128.20f, -102.40f}, {-113.50f, -112.20f}, {-98.20f, -120.90f}, {-82.30f, -128.60f}, {-65.90f, -135.20f}};

static const nav_icon_data_t NAV_ICON_DATA[NAV_RENDER_COUNT] = {
    [NAV_RENDER_STRAIGHT] = { nav_icon_straight_main, 1, NULL, 0, {0.0f, -130.0f} },
    [NAV_RENDER_TURN_RIGHT] = { nav_icon_turn_right_main, 3, NULL, 0, {70.0f, -120.0f} },
    [NAV_RENDER_TURN_LEFT] = { nav_icon_turn_left_main, 3, NULL, 0, {-70.0f, -120.0f} },
    [NAV_RENDER_TURN_SLIGHT_RIGHT] = { nav_icon_turn_slight_right_main, 3, NULL, 0, {34.6f, -145.5f} },
    [NAV_RENDER_TURN_SLIGHT_LEFT] = { nav_icon_turn_slight_left_main, 3, NULL, 0, {-34.6f, -145.5f} },
    [NAV_RENDER_U_TURN_RIGHT] = { nav_icon_u_turn_right_main, 3, NULL, 0, {70.0f, -130.0f} },
    [NAV_RENDER_U_TURN_LEFT] = { nav_icon_u_turn_left_main, 3, NULL, 0, {-70.0f, -130.0f} },
    [NAV_RENDER_ROUNDABOUT_RIGHT] = { nav_icon_roundabout_right_main, 5, NULL, 0, {40.0f, -145.0f} },
    [NAV_RENDER_ROUNDABOUT_STRAIGHT] = { nav_icon_roundabout_straight_main, 5, NULL, 0, {-0.0f, -165.0f} },
    [NAV_RENDER_ROUNDABOUT_LEFT] = { nav_icon_roundabout_left_main, 5, NULL, 0, {-55.0f, -136.6f} },
    [NAV_RENDER_RIGHT_MERGE] = { nav_icon_right_merge_main, 1, nav_icon_right_merge_secondary, 10, {70.0f, -130.0f} },
    [NAV_RENDER_MERGE_LEFT] = { nav_icon_merge_left_main, 1, nav_icon_merge_left_secondary, 10, {-70.0f, -130.0f} },
};

// Longest maneuver, so the renderer can size its route buffer off the data.
#define NAV_ICON_MAX_SEGMENTS 5

static const nav_pt_t NAV_ARROWHEAD_PERIMETER[] = {{-47.00f, 180.00f}, {-137.00f, 270.00f}, {-203.00f, 204.00f}, {0.00f, 0.00f}, {203.00f, 204.00f}, {137.00f, 270.00f}, {47.00f, 180.00f}};
#define NAV_ARROWHEAD_VERT_COUNT 7
static const nav_pt_t NAV_ARROWHEAD_TIP = {0.0f, 0.0f};
static const float NAV_ARROWHEAD_HEAD_BASE_HALF_WIDTH = 47.0f;
static const float NAV_ARROWHEAD_HEAD_BASE_DEPTH = 180.0f;

