// ESP32/LVGL round-display arrow animation demo.
//
// Shape data: ICONS/ARROWHEAD come from icons-data.js, generated by
// Google Icons Archive/Icon JSON/build_icons.py from maneuvers.json (the
// canonical, hand-edited maneuver definitions). To change a maneuver's
// shape, edit maneuvers.json and rerun build_icons.py -- this file is a
// pure consumer of the baked output, it does no geometry generation.
//
// RENDERING IS NOT SVG. Everything is drawn through lvgl_shim.js, whose
// primitives map 1:1 onto LVGL calls, into a canvas sized to the REAL panel
// resolution (DEMO_PARAMS.panel.sizes) and CSS-scaled for viewing. What you
// see is pixel-for-pixel what the device draws. See lvgl_shim.js for why the
// route line is built from quads and discs rather than stroked, and why the
// arrowhead is triangulated.
//
// Consequently there is no scene graph and no transform attribute: the
// camera is a plain pose that worldToScreen() applies per point, which is
// exactly what the C port does.
//
// Route model: ONE continuous, ever-growing world-space polyline
// (routePoints/cumDist below) -- every maneuver's transformed points get
// appended to it.
//
// ONE SEGMENT AT A TIME. At rest the rendered window is exactly the
// current maneuver: baseDist == its startDist, headDist == its endDist.
// Nothing trails off the back. During a transition baseDist eases from the
// OLD segment's start to the new one's, so the old segment retracts from
// behind while the new one draws ahead -- one continuous worm, no hard cut
// and no leftovers.
//
// CAMERA: a keyframed POSE per maneuver, not a per-frame sample of the
// path. The old camera read the base point's local tangent every frame, so
// the display spun through every wiggle of the geometry -- a roundabout
// rotated through its whole sweep, and even a straight-through roundabout
// (net rotation 0, which should hold perfectly still) swung hard in and
// back out. Instead each maneuver gets ONE pose, computed once when it is
// added, and all motion is a single eased interpolation between poses.
// Smoothness is then a property of the interpolation rather than something
// we hope a sampled tangent gives us.
//
// FIXED SCALE. There is no camera zoom: every maneuver is drawn at the same
// scale, guaranteed to fit the round display by check_fit() in
// build_icons.py. Size constancy matters more than fitting tightly on a
// display that gets glanced at for a fraction of a second. It also keeps
// stroke width and arrowhead size constant (set once, never recomputed).

const displaysEl = document.getElementById("displays");
const buttonsEl = document.getElementById("buttons");
const NAMES = Object.fromEntries(Object.entries(ICONS).map(([k, v]) => [k, v.name]));

// The authored coordinate system: maneuvers are designed to fit a 600-unit
// circle (build_icons.py's DISPLAY_DIAMETER). Route units -> panel pixels is
// the ONLY scale conversion in the renderer.
const DESIGN_DIAMETER = 600;

function rotatePoint([x, y], [ox, oy], angle) {
  const dx = x - ox, dy = y - oy;
  const c = Math.cos(angle), s = Math.sin(angle);
  return [ox + dx * c - dy * s, oy + dx * s + dy * c];
}

function heading(pFrom, pTo) {
  return Math.atan2(pTo[1] - pFrom[1], pTo[0] - pFrom[0]);
}

// normalize radians to (-PI, PI] -- the JS twin of build_icons.py's
// norm_angle(). Used to take the SHORT way round when interpolating
// rotation; without it a u-turn's 180deg pose change can unwind the long
// way and spin the display backwards through the whole route.
function normAngle(a) {
  a = a % (2 * Math.PI);
  if (a > Math.PI) a -= 2 * Math.PI;
  if (a <= -Math.PI) a += 2 * Math.PI;
  return a;
}

function clamp(v, lo, hi) {
  return Math.max(lo, Math.min(hi, v));
}

function lerp(a, b, t) {
  return a + (b - a) * t;
}

function easeInOutCubic(t) {
  return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
}

// --- rendering knobs, from params.js (no in-page UI; edit + reload) -----

const headScale = DEMO_PARAMS.arrowheadScale;
const displayScale = DEMO_PARAMS.displayScale;
const verticalOffset = DEMO_PARAMS.verticalOffset;
const arrowVerticalOffsetFrac = DEMO_PARAMS.arrowVerticalOffset || 0;
const frameCenterOverrides = DEMO_PARAMS.frameCenter || {};
const revealSpeed = DEMO_PARAMS.revealSpeed;
const minRevealMs = DEMO_PARAMS.minRevealMs;
const maxRevealMs = DEMO_PARAMS.maxRevealMs;
const lineThickness = DEMO_PARAMS.lineThickness;

const PANEL = DEMO_PARAMS.panel || { sizes: [240] };

// One or more panel resolutions, rendered side by side from the SAME
// animation state. `size` (singular) stays accepted so a single-panel config
// still works.
const PANEL_SIZES = PANEL.sizes || [PANEL.size || 240];

// Sub-pixel growth that makes adjacent filled pieces overlap instead of abut.
// Without it every shared edge in the arrowhead's triangulation renders as a
// grey hairline -- see lvgl_shim.js's SEAMS note.
const SEAM = PANEL.seamOverlap != null ? PANEL.seamOverlap : 0.5;

const COLORS = DEMO_PARAMS.colors || {
  background: "#000000",
  route: "#ffffff",
  secondary: "#6b7280",
  referenceCircle: "#3a3a3a",
};

// route units -> panel pixels, for the first (or only) panel. Per-view code
// uses view.px instead; this stays for the single-panel case and for callers
// that just want the authoring scale.
const PX = PANEL_SIZES[0] / DESIGN_DIAMETER;

// The draw targets, filled in by init(). Each is
// { size, px, target } -- `target` being the LV handle to select with LV.use.
const views = [];

// How far back from the arrowhead's tip its glyph is already at full width
// (ARROWHEAD's head_base_depth, scaled). The rendered line is trimmed
// short by this much at its head end -- not the arrowhead moved -- so the
// arrowhead's tip still lands exactly on the route's true current end and
// the line's flat end sits back under the glyph instead of poking out past
// its point. Constant, because the scale is fixed.
const HEAD_DEPTH = (ARROWHEAD.head_base_depth || 0) * headScale;

// The arrowhead is a rigid barbed glyph, so its triangulation is computed
// once here and reused every frame -- only its 7 vertices move. On device
// this is a const index array in flash.
const HEAD_TRIS = LV.triangulate(ARROWHEAD.perimeter);

// =========================================================================
// Route: one continuous world-space polyline + arc-length bookkeeping.
//
// cumDist holds ABSOLUTE arc lengths from the route's original origin, and
// stays absolute even after pruning drops points off the front -- so every
// maneuver's cached startDist/endDist remains valid for the life of the
// run and nothing needs rebasing.
// =========================================================================

let routePoints = []; // [[x,y], ...] world space
let cumDist = []; // cumDist[i] = absolute arc length at routePoints[i]
let maneuvers = []; // { key, startDist, endDist, pose, secondaryPoints }

function totalDist() {
  return cumDist.length ? cumDist[cumDist.length - 1] : 0;
}

// appends `pts` (world space); if routePoints is non-empty, pts[0] must
// coincide with the current last point (shared boundary) and is skipped.
function appendPoints(pts) {
  const startIdx = routePoints.length ? 1 : 0;
  for (let i = startIdx; i < pts.length; i++) {
    const p = pts[i];
    const prev = routePoints[routePoints.length - 1];
    const d = prev ? Math.hypot(p[0] - prev[0], p[1] - prev[1]) : 0;
    cumDist.push((cumDist.length ? cumDist[cumDist.length - 1] : 0) + d);
    routePoints.push(p);
  }
}

// index of the first route point at or past `dist` (binary search).
function indexAtDist(dist) {
  let lo = 1, hi = cumDist.length - 1;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (cumDist[mid] < dist) lo = mid + 1;
    else hi = mid;
  }
  return lo;
}

// point + local tangent heading at arc-length `dist` along the route.
// routePoints is a polyline, so this is exact -- no curve-flattening
// approximation involved.
function pointAndHeadingAtDist(dist) {
  if (routePoints.length < 2) return { point: routePoints[0] || [0, 0], heading: -Math.PI / 2 };
  dist = clamp(dist, cumDist[0], totalDist());
  const i = indexAtDist(dist);
  const a = routePoints[i - 1], b = routePoints[i];
  const segStart = cumDist[i - 1], segEnd = cumDist[i];
  const segLen = segEnd - segStart;
  const t = segLen > 0 ? (dist - segStart) / segLen : 0;
  return { point: [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t], heading: heading(a, b) };
}

// the rendered window's point list between two arc-length distances.
// Binary-searches the start instead of rescanning the whole route, so cost
// is O(log n + points actually drawn).
function sliceWindow(fromDist, toDist) {
  const total = totalDist();
  const lo = cumDist.length ? cumDist[0] : 0;
  fromDist = clamp(fromDist, lo, total);
  toDist = clamp(toDist, lo, total);
  if (toDist <= fromDist) return [pointAndHeadingAtDist(fromDist).point];
  const pts = [pointAndHeadingAtDist(fromDist).point];
  for (let i = indexAtDist(fromDist); i < routePoints.length && cumDist[i] < toDist; i++) {
    if (cumDist[i] > fromDist) pts.push(routePoints[i]);
  }
  pts.push(pointAndHeadingAtDist(toDist).point);
  return pts;
}

// Drops route points that are fully behind the window. Nothing can ever
// look backwards past baseDist again (the base only ever moves forward),
// so anything before the segment straddling it is provably dead. Keeps the
// route's memory bounded by the longest single maneuver rather than by how
// long the demo has been running -- the device has no headroom for an
// ever-growing polyline.
function pruneBefore(dist) {
  if (routePoints.length < 3 || dist <= cumDist[0]) return;
  const keep = indexAtDist(dist) - 1; // segment straddling `dist` must survive
  if (keep <= 0) return;
  routePoints.splice(0, keep);
  cumDist.splice(0, keep);
  while (maneuvers.length > 1 && maneuvers[0].endDist < cumDist[0]) maneuvers.shift();
}

// placement transform for a new maneuver's local points, continuing
// tangentially from wherever the route currently ends.
function computeTransform(localMain) {
  const base0 = localMain[0];
  const base1 = localMain[1];
  const headingNew = heading(base0, base1);
  let rotation = 0, anchor = base0;
  if (routePoints.length) {
    const tipPrev = routePoints[routePoints.length - 1];
    const preTipPrev = routePoints[routePoints.length - 2] || tipPrev;
    rotation = heading(preTipPrev, tipPrev) - headingNew;
    anchor = tipPrev;
  }
  return { rotation, anchor, base0 };
}

function transformPoint(p, t) {
  const r = rotatePoint(p, t.base0, t.rotation);
  return [r[0] + (t.anchor[0] - t.base0[0]), r[1] + (t.anchor[1] - t.base0[1])];
}

// --- camera pose -------------------------------------------------------

// A maneuver's framing, computed once from its world-space points:
//   rot -- the rotation the camera applies to the world, chosen so this
//          maneuver's ENTRY heading points screen-up. Constant for the
//          whole maneuver, which is precisely what stops the spin.
//   cx,cy -- the world point that should land at screen centre, obtained by
//          taking the maneuver's framing point in its own LOCAL frame and
//          pushing it through the same placement transform as its geometry.
//
// Working in the local frame is what makes framing configurable. A maneuver
// is authored starting at (0,0) heading up, and the camera rotates so the
// entry heading points up -- so local frame IS camera frame, and a single
// local-space [x,y] is a stable, chaining-independent framing target that can
// be hand-tuned per maneuver (DEMO_PARAMS.frameCenter) rather than being
// whatever the bounding box happens to compute.
function computePose(key, data, t) {
  const entryHeading = heading(
    transformPoint(data.main_path[0], t),
    transformPoint(data.main_path[1], t)
  );
  const local = frameCenterOverrides[key] || data.frame_center || [0, 0];
  const [cx, cy] = transformPoint(local, t);
  return { cx, cy, rot: -Math.PI / 2 - entryHeading };
}

// The camera, as an explicit function instead of an SVG transform list.
// Order matches what the old `scale(...) translate(0,vo) rotate(...)
// translate(-cx,-cy)` did, reading right to left: recentre on the pose
// point, rotate to entry-heading-up, shift by verticalOffset in pure screen
// space, apply the uniform displayScale, then convert route units to panel
// pixels about the panel centre.
//
// On device this is the same handful of multiply-adds with one sin/cos per
// FRAME (not per point) -- hoist `c`/`s` exactly as cameraBasis() does.
function cameraBasis(cam) {
  return { c: Math.cos(cam.rot), s: Math.sin(cam.rot) };
}

// `view` supplies the only resolution-dependent terms (panel centre and
// units-per-pixel), which is what lets one camera pose drive several panels.
const DEFAULT_VIEW = { size: PANEL_SIZES[0], px: PX };

// --- compass ring --------------------------------------------------------

// Fixed screen-space graduated ring at the dial's outer edge, plus a red
// triangle that swings to the current screen-space direction of true north.
// Ticks stay put (a bezel scale, like referenceCircle); only the north mark
// rotates. Cost is O(tickCount) straight-line draws + one filled triangle,
// once per frame -- no trig beyond what's already needed for the tick angles
// (computed once from a fixed count, not re-derived from anything dynamic).
function drawCompassRing(view) {
  const cp = DEMO_PARAMS.compass;
  if (!cp || !cp.show) return;
  const half = view.size / 2;
  const cx = half, cy = half;

  for (let i = 0; i < cp.tickCount; i++) {
    // i=0 sits at screen-up, matching north-up at rest (cur.rot = 0).
    const angle = (i / cp.tickCount) * Math.PI * 2 - Math.PI / 2;
    const isMajor = i % cp.majorEvery === 0;
    const len = (isMajor ? cp.majorLength : cp.minorLength) * half;
    const w = Math.max(1, (isMajor ? cp.majorWidth : cp.minorWidth) * view.px);
    const c = Math.cos(angle), s = Math.sin(angle);
    LV.strokeLine(
      cx + c * half, cy + s * half,
      cx + c * (half - len), cy + s * (half - len),
      w, cp.color
    );
  }

  // North is an independent screen-space heading (see `northHeading` below),
  // not derived from the camera -- 0 = up, increasing clockwise. It has no
  // relationship to cur.rot; whatever eventually feeds it (real heading data)
  // just needs to keep supplying that one angle.
  const screenAngle = northHeading - Math.PI / 2;
  const nc = Math.cos(screenAngle), ns = Math.sin(screenAngle);
  const tipR = half * (1 - cp.northLength);
  const tip = [cx + nc * tipR, cy + ns * tipR];
  const baseHalfW = cp.northWidth * half;
  const px = -ns, py = nc; // perpendicular to the radial direction, for the base corners
  const baseA = [cx + nc * half + px * baseHalfW, cy + ns * half + py * baseHalfW];
  const baseB = [cx + nc * half - px * baseHalfW, cy + ns * half - py * baseHalfW];
  LV.fillTriangle(baseA, baseB, tip, cp.northColor);
}

function worldToScreen(p, cam, basis, view = DEFAULT_VIEW) {
  const dx = p[0] - cam.cx, dy = p[1] - cam.cy;
  const rx = dx * basis.c - dy * basis.s;
  const ry = dx * basis.s + dy * basis.c;
  const sx = rx * displayScale;
  const sy = (ry + verticalOffset) * displayScale;
  const half = view.size / 2;
  return [half + sx * view.px, half + sy * view.px + arrowVerticalOffsetFrac * view.size];
}

// --- arrowhead -------------------------------------------------------

// ARROWHEAD is authored tip-at-origin, pointing "up" (-y). Scale is applied
// in local space, before rotation/translation, so the tip stays pinned to
// tipPoint.
function arrowheadPolygonPoints(tipPoint, travelAngle) {
  const localForward = -Math.PI / 2;
  const rotation = travelAngle - localForward;
  return ARROWHEAD.perimeter.map((p) => {
    const scaled = [p[0] * headScale, p[1] * headScale];
    const r = rotatePoint(scaled, ARROWHEAD.tip, rotation);
    return [r[0] + tipPoint[0], r[1] + tipPoint[1]];
  });
}

// =========================================================================
// The tween: ONE persistent rAF loop with retargetable endpoints.
//
// `cur` is the live rendered state -- the single source of truth for
// "where are we". A maneuver arriving mid-flight re-bases `from` off the
// CURRENT INTERPOLATED state rather than starting a second loop, so motion
// bends toward the new target instead of snapping.
// =========================================================================

const cur = { baseDist: 0, headDist: 0, cx: 0, cy: 0, rot: 0 };
let from = null, to = null, tweenStart = 0, tweenDur = 0, running = false;

// --- compass heading ---------------------------------------------------
//
// northHeading is the ONLY input drawCompassRing() reads for where north
// points (screen radians, 0 = up, clockwise). It is intentionally not
// derived from cur.rot, the camera, or anything else in the maneuver state --
// a real heading feed will assign it directly. Until that feed exists, it is
// driven by a slow constant-rate placeholder spin, on its own rAF loop so it
// keeps moving even when no maneuver tween is running.
const COMPASS_PLACEHOLDER_RPM = 20;
let northHeading = 0;
let lastCompassSpinTime = null;

function spinCompassPlaceholder(now) {
  if (lastCompassSpinTime != null) {
    const dtMs = now - lastCompassSpinTime;
    northHeading = (northHeading + (COMPASS_PLACEHOLDER_RPM * 2 * Math.PI / 60000) * dtMs) % (2 * Math.PI);
    if (!running) renderFrame(); // the tween loop already redraws every frame when it's active
  }
  lastCompassSpinTime = now;
  requestAnimationFrame(spinCompassPlaceholder);
}

// One panel's worth of drawing, immediate mode, back to front. This is the
// function that becomes the LVGL draw callback essentially verbatim -- on
// device there is exactly one view, and `view` is a compile-time constant.
function renderView(view) {
  LV.clear(COLORS.background);

  // Static scale gauge. Drawn FIRST (so it sits behind) and in pure screen
  // space -- it is a fixed viewport ring, unaffected by the camera or by
  // displayScale, which is the point of it.
  const rc = DEMO_PARAMS.referenceCircle;
  if (rc && rc.show) {
    const half = view.size / 2;
    LV.strokeArcRing(half, half, half * rc.radiusFraction,
      Math.max(1, (rc.thickness || 2) * view.px), COLORS.referenceCircle);
  }

  drawCompassRing(view);

  const basis = cameraBasis(cur);
  const toScreen = (p) => worldToScreen(p, cur, basis, view);

  // merges only: the side lane the main route merges with
  for (const m of maneuvers) {
    if (m.secondaryPoints.length > 1 && m.endDist > cur.baseDist && m.startDist < cur.headDist) {
      LV.strokePolyline(m.secondaryPoints.map(toScreen),
        lineThickness * 0.7 * displayScale * view.px, COLORS.secondary, SEAM);
    }
  }

  const trimmedHead = Math.max(cur.baseDist, cur.headDist - HEAD_DEPTH);
  LV.strokePolyline(sliceWindow(cur.baseDist, trimmedHead).map(toScreen),
    lineThickness * displayScale * view.px, COLORS.route, SEAM);

  const head = pointAndHeadingAtDist(cur.headDist);
  const headVerts = arrowheadPolygonPoints(head.point, head.heading).map(toScreen);
  LV.fillTriangulated(headVerts, HEAD_TRIS, COLORS.route, SEAM);
}

// Draws every configured panel from the one shared pose, so the side-by-side
// resolutions stay in exact lockstep -- any difference you see between them
// is a rasterization difference, never a timing one.
function renderFrame() {
  for (const v of views) {
    LV.use(v.target);
    renderView(v);
  }
}

function tick(now) {
  const t = tweenDur > 0 ? Math.min(1, (now - tweenStart) / tweenDur) : 1;
  const e = easeInOutCubic(t);
  cur.baseDist = lerp(from.baseDist, to.baseDist, e);
  cur.headDist = lerp(from.headDist, to.headDist, e);
  cur.cx = lerp(from.cx, to.cx, e);
  cur.cy = lerp(from.cy, to.cy, e);
  cur.rot = lerp(from.rot, to.rot, e);
  renderFrame();

  if (t < 1) {
    requestAnimationFrame(tick);
  } else {
    running = false;
    Object.assign(cur, to);
    renderFrame();
    pruneBefore(cur.baseDist);
  }
}

function retarget(target, durationMs) {
  from = { ...cur };
  // Take the short way round: express the goal rotation as the current one
  // plus a delta normalized to (-PI, PI].
  to = { ...target, rot: from.rot + normAngle(target.rot - from.rot) };
  tweenStart = performance.now();
  tweenDur = durationMs;
  if (!running) {
    running = true;
    requestAnimationFrame(tick);
  }
}

// --- adding maneuvers ------------------------------------------------

function addManeuver(key, { animate = true } = {}) {
  const data = ICONS[key];
  const localMain = data.main_path.map((p) => p.slice());
  const localSecondary = (data.secondary_path || []).map((p) => p.slice());
  const t = computeTransform(localMain);
  const worldMain = localMain.map((p) => transformPoint(p, t));
  const worldSecondary = localSecondary.map((p) => transformPoint(p, t));

  const startDist = totalDist();
  appendPoints(worldMain);
  const endDist = totalDist();

  const pose = computePose(key, data, t);

  maneuvers.push({ key, startDist, endDist, pose, secondaryPoints: worldSecondary });

  const target = { baseDist: startDist, headDist: endDist, ...pose };

  if (!animate) {
    Object.assign(cur, target);
    renderFrame();
    return;
  }

  // Reveal rate roughly constant across maneuvers: a fixed duration made an
  // 864-unit roundabout sweep 3.6x faster than a 240-unit straight.
  const duration = clamp((endDist - startDist) / revealSpeed, minRevealMs, maxRevealMs);
  retarget(target, duration);
}

// --- setup -------------------------------------------------------------

function init() {
  // One canvas per configured panel. Each backing store is the REAL panel
  // resolution; CSS only scales it for viewing, so the demo stays a true
  // pixel preview of each device.
  //
  // In "proportional" mode the largest panel gets viewPx and the rest are
  // scaled by pixel count, so one device pixel is the same size on screen in
  // every preview -- a 244 panel then genuinely looks smaller than a 460 one,
  // which is the honest comparison. "matched" gives them all viewPx instead.
  const viewPx = PANEL.viewPx || PANEL_SIZES[0] * (PANEL.zoom || 1);
  const biggest = Math.max(...PANEL_SIZES);
  const cssFor = (size) =>
    PANEL.viewMode === "matched" ? viewPx : viewPx * (size / biggest);

  for (const size of PANEL_SIZES) {
    const wrap = document.createElement("div");
    wrap.className = "panel";

    const css = cssFor(size);

    const disp = document.createElement("div");
    disp.className = "display";
    disp.style.width = css + "px";
    disp.style.height = css + "px";

    const canvas = document.createElement("canvas");
    canvas.width = size;
    canvas.height = size;
    canvas.style.width = css + "px";
    canvas.style.height = css + "px";
    disp.appendChild(canvas);

    const label = document.createElement("div");
    label.className = "label";
    label.textContent = size + " x " + size;

    wrap.appendChild(disp);
    wrap.appendChild(label);
    displaysEl.appendChild(wrap);

    views.push({ size, px: size / DESIGN_DIAMETER, target: LV.target(canvas), canvas });
  }

  addManeuver("straight", { animate: false });
  requestAnimationFrame(spinCompassPlaceholder);

  const order = [
    "straight",
    "turn_left",
    "turn_right",
    "turn_slight_left",
    "turn_slight_right",
    "u_turn_left",
    "u_turn_right",
    "roundabout_left",
    "roundabout_straight",
    "roundabout_right",
    "merge_left",
    "right_merge",
  ];
  for (const key of order) {
    const btn = document.createElement("button");
    btn.textContent = NAMES[key];
    btn.addEventListener("click", () => addManeuver(key));
    buttonsEl.appendChild(btn);
  }
}

init();
