"""
Rasterizes the SVG icons declared in design/icons/icons_manifest.json into per-screen-profile LVGL
C arrays, one generated header per profile under firmware/gui/generated/. This is the SVG-to-device
twin of Google Icons Archive/Icon JSON/build_icons.py (which handles the turn-by-turn maneuver
arrows as *procedural vector* data, never bitmaps -- see docs/OpenApex_SPEC.md §16.6 for why
that pair stays off this path). Anything with a shape that doesn't reduce to a handful of line/arc
primitives (status glyphs, map pins, battery/bluetooth states, ...) belongs here instead.

Pipeline per (icon x screen profile):
  1. Rasterize the source SVG with resvg (via the resvg-py bindings -- a prebuilt binary wheel, no
     system Cairo/Inkscape dependency) at the profile's pixel size.
  2. Take the alpha channel only, as an LVGL A8 coverage mask -- these are flat single-colour
     Material Symbols glyphs, so alpha *is* the shape; colour is applied at draw time via LVGL's
     image recolor/tint (same trick firmware/gui/nav_renderer.cpp's build_arrowhead_mask() already
     uses for the arrowhead). This keeps per-icon flash cost to 1 byte/px instead of 4, and means one
     mask can be recoloured for different themes/states without a second raster.
  3. Emit a `static const lv_image_dsc_t` per icon into firmware/gui/generated/icons_<profile>.h,
     plus a name -> descriptor lookup table, mirroring nav_icons_data.h's generated-table shape.

Run: python tools/build_icon_raster.py   (reads design/icons/icons_manifest.json, writes
firmware/gui/generated/icons_<profile>.h for every profile in SCREEN_PROFILES below)

Generated headers ARE checked into git, same call as nav_icons_data.h: the firmware build (PlatformIO
C3 target, or a real S3 build later) must not require Python/resvg/Pillow to be installed. Re-run this
script and commit the diff whenever icons_manifest.json or a source SVG changes.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
MANIFEST_PATH = os.path.join(REPO_ROOT, "design", "icons", "icons_manifest.json")
OUT_DIR = os.path.join(REPO_ROOT, "firmware", "gui", "generated")

try:
    import resvg_py
except ImportError:
    raise ImportError(
        "Need resvg-py: python -m pip install -r tools/requirements-icons.txt")
try:
    from PIL import Image
except ImportError:
    raise ImportError(
        "Need Pillow: python -m pip install -r tools/requirements-icons.txt")

# --- screen profile registry -------------------------------------------------------------------
# Hand-synced twin of firmware/main/board_profile.h's BOARD_DISP_WIDTH/HEIGHT + BOARD_GFX_TIER
# (there is no way to parse C preprocessor state from Python without a compiler run, so like
# build_icons.py's FRAME_CENTER_OVERRIDES this is kept in sync by hand -- update both together).
# `header` names the profile's board_profile.h macro purely for the doc comment emitted into the
# generated file; it has no build-system effect.
REFERENCE_WIDTH_PX = 240.0  # icons_manifest.json's size_240 is authored against this profile.

SCREEN_PROFILES = {
    "prototype_c3_gc9a01": {
        "width": 240, "height": 240,
        "header_macro": "BOARD_PROFILE_PROTOTYPE_C3_GC9A01",
    },
    "s3_amoled_175": {
        "width": 466, "height": 466,
        "header_macro": "BOARD_PROFILE_S3_AMOLED_175",
    },
}


def rasterize_alpha(svg_path, size_px):
    """Rasterizes svg_path to an RGBA PNG at size_px x size_px via resvg, returns the alpha
    channel as a row-major bytes buffer (one byte per pixel, LVGL A8 layout)."""
    with open(svg_path, encoding="utf-8") as f:
        svg_string = f.read()
    png_bytes = resvg_py.svg_to_bytes(svg_string=svg_string, width=size_px, height=size_px)
    import io
    img = Image.open(io.BytesIO(bytes(png_bytes))).convert("RGBA")
    if img.size != (size_px, size_px):
        raise SystemExit(
            f"{svg_path}: resvg returned {img.size}, expected {size_px}x{size_px} "
            "(non-square viewBox? icons_manifest.json assumes square source art)")
    return img.getchannel("A").tobytes()


def emit_profile_header(profile_name, profile, icons):
    width = profile["width"]
    height = profile["height"]
    scale = width / REFERENCE_WIDTH_PX

    lines = [
        "// Auto-generated by tools/build_icon_raster.py from design/icons/icons_manifest.json --",
        "// do not edit by hand, edit icons_manifest.json (or the source SVGs it points at) and",
        "// re-run the script instead.",
        f"// Screen profile: {profile_name} ({profile['header_macro']} in board_profile.h),",
        f"// {width}x{height}, icon scale {scale:.4f}x relative to the {REFERENCE_WIDTH_PX:.0f}px",
        "// reference profile icons_manifest.json's size_240 values are authored against.",
        "#pragma once",
        "",
        "#ifdef __has_include",
        '    #if __has_include("lvgl.h")',
        "        #if !defined(LV_LVGL_H_INCLUDE_SIMPLE) && !defined(LV_LVGL_H_INCLUDE_SYSTEM)",
        "            #define LV_LVGL_H_INCLUDE_SIMPLE",
        "        #endif",
        "    #endif",
        "#endif",
        "",
        "#if defined(LV_LVGL_H_INCLUDE_SIMPLE)",
        '#include "lvgl.h"',
        "#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)",
        "#include <lvgl.h>",
        "#else",
        '#include "lvgl/lvgl.h"',
        "#endif",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef enum {",
    ]
    for name in icons:
        lines.append(f"    ICON_{name.upper()},")
    lines.append("    ICON_COUNT,")
    lines.append("} icon_id_t;")
    lines.append("")
    lines.append("// name lookup, index-matched with icon_id_t -- for logging/debug only.")
    lines.append("static const char *const ICON_NAMES[ICON_COUNT] = {")
    for name in icons:
        lines.append(f'    "{name}",')
    lines.append("};")
    lines.append("")

    total_bytes = 0
    for name, entry in icons.items():
        size_px = max(1, round(entry["size_240"] * scale))
        alpha = rasterize_alpha(os.path.join(REPO_ROOT, entry["svg"]), size_px)
        total_bytes += len(alpha)
        varname = f"icon_{name}_map"
        lines.append(f"// {name}: {size_px}x{size_px}px, A8, {len(alpha)} bytes")
        lines.append(f"static const uint8_t {varname}[] = {{")
        row = []
        for i, b in enumerate(alpha):
            row.append(f"0x{b:02x},")
            if len(row) == 16:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
        lines.append("")

    lines.append("static const lv_image_dsc_t ICON_DESC[ICON_COUNT] = {")
    for name, entry in icons.items():
        size_px = max(1, round(entry["size_240"] * scale))
        varname = f"icon_{name}_map"
        lines.append(
            f"    [ICON_{name.upper()}] = {{ .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, "
            f".cf = LV_COLOR_FORMAT_A8, .w = {size_px}, .h = {size_px}, .stride = {size_px} }}, "
            f".data_size = sizeof({varname}), .data = {varname} }},"
        )
    lines.append("};")
    lines.append("")
    lines.append(f"// Total icon payload for this profile: {total_bytes} bytes ({total_bytes / 1024:.1f} KiB).")
    lines.append("")

    out_path = os.path.join(OUT_DIR, f"icons_{profile_name}.h")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}  ({total_bytes} bytes, {len(icons)} icons)")


def main():
    with open(MANIFEST_PATH, encoding="utf-8") as f:
        manifest = json.load(f)
    icons = manifest["icons"]

    for name, entry in icons.items():
        svg_path = os.path.join(REPO_ROOT, entry["svg"])
        if not os.path.isfile(svg_path):
            raise SystemExit(f"icons_manifest.json: icon {name!r} points at missing file {svg_path}")
        if "size_240" not in entry:
            raise SystemExit(f"icons_manifest.json: icon {name!r} is missing size_240")

    for profile_name, profile in SCREEN_PROFILES.items():
        emit_profile_header(profile_name, profile, icons)


if __name__ == "__main__":
    main()
